---
title: "Explore Coupling Coefficient"
author: "Fengling Hu"
output: html_document
---

```{r}
library(tidyverse)
library(ANTsRCore)
library(extrantsr)
library(IMCo)
library(here)
library(matrixStats)
library(freesurfer)
```

# Distribution of coupling coefficients
## Functions
```{r}
load_coupling_vals <- function (dir, pca_type = c("global_wcov", "unscaled_wcor"), n = 50, p = 0.5) {
  coupling_files <- file.path(here(".."), dir, "output/niftis/coupled/", pca_type) %>% 
    list.files(full.names = TRUE) %>% 
    sample(n)
  ants_list <- check_ants(coupling_files)
  
  vec_list <- vector("list", length = n)
  for (i in 1:n) {
    current <- ants_list[[i]] %>% as.array() %>% as.vector()
    vec_list[[i]] <- current[current != 0]
  }
  
  vals <- vec_list %>% unlist()
  vals_samp <- vals %>% sample(p * length(vals))
  
  return(vals_samp)
}

plot_densities <- function (raw, transformed) {
  if (typeof(transformed) != "list") {
    stop("Transformed must be of type \'list\'")
  }
  coupling_vals <- data.frame(raw = raw)
  for (i in 1:length(transformed)) {
    coupling_vals <- coupling_vals %>% 
      cbind(transformed[[i]])
    print(var(transformed[[i]]))
  }
  
  names(coupling_vals) = c("raw", paste0("tx", 1:length(transformed)))
  print(summary(coupling_vals))
  
  coupling_vals <- coupling_vals %>% 
    pivot_longer(everything(),
                 names_to = "type",
                 values_to = "coupling_vals")
  
  ggplot(data = coupling_vals, aes(x = coupling_vals, fill = type)) +
    geom_density(alpha = 0.4) +
    theme_classic()
}
```

## Run
```{r}
isla_abs_g <- load_coupling_vals("ALFF_IDEMO_ISLA_abs", "global_wcov", n = 50, p = 0.01)
isla_abs_u <- load_coupling_vals("ALFF_IDEMO_ISLA_abs", "unscaled_wcor", n = 50, p = 0.01)

isla_abs_g_norm <- isla_abs_g * 1.5 - 0.5
isla_abs_u_norm <- isla_abs_u * 1.5 - 0.5

plot_densities(isla_abs_g, list(isla_abs_g_norm %>% log(),
                                isla_abs_g_norm ^ 2,
                                log(isla_abs_g_norm) - log(1 - isla_abs_g_norm),
                                isla_abs_g_norm ^ .5 - (1 - isla_abs_g_norm) ^ .5))
plot_densities(isla_abs_u, list(isla_abs_u_norm %>% log(),
                                isla_abs_u_norm ^ 2,
                                log(isla_abs_u_norm) - log(1 - isla_abs_u_norm),
                                isla_abs_u_norm ^ .5 - (1 - isla_abs_u_norm) ^ .5))
```

```{r}
isla_g <- load_coupling_vals("ALFF_IDEMO_ISLA_abs", "global_wcov", n = 50, p = 0.01)
isla_u <- load_coupling_vals("ALFF_IDEMO_ISLA", "unscaled_wcor", n = 50, p = 0.01)

isla_g_norm <- isla_g * 1.5 - 0.5
isla_u_norm <- isla_u * 1.5 - 0.5

plot_densities(isla_g, list(isla_g_norm %>% log(),
                            isla_g_norm ^ 2,
                            log(isla_g_norm) - log(1 - isla_g_norm),
                            isla_g_norm ^ .5 - (1 - isla_g_norm) ^ .5))
plot_densities(isla_u, list(isla_u_norm %>% log(),
                            isla_u_norm ^ 2,
                            log(isla_u_norm) - log(1 - isla_u_norm),
                            isla_u_norm ^ .5 - (1 - isla_u_norm) ^ .5))
```

# Exploring freesurfer projections
```{r}
fs_image_dir <- here("../input/spin_test/yeo7_regions/")
yeo7_1_arr <- check_ants(file.path(fs_image_dir, "lh.yeo7_1.nii.gz")) %>% as.array()
yeo7_1_mgh_arr <- check_ants(file.path(fs_image_dir, "lh.yeo7_1.mgh")) %>% as.array()
pval_arr <- check_ants(file.path(fs_image_dir, "pvals/adjusted/rh.global_wcov_sex_fdr05.nii.gz")) %>% as.array()
```

