# Abstract {-}

  When individual subjects are imaged with multiple modalities, biological information is present not only within each modality, but also between modalities -- that is, in how modalities covary at the voxel level. Previous studies have shown that local covariance structures between modalities, or intermodal coupling (IMCo), can be summarized for two modalities, and that two-modality IMCo reveals otherwise undiscovered patterns in neurodevelopment and certain diseases. However, previous IMCo methods are based on the slopes of local weighted linear regression lines, which are inherently asymmetric and limited to the two-modality setting. Here, we present a generalization of IMCo estimation which uses local covariance decompositions to define a symmetric, voxel-wise coupling coefficient that is valid for two or more modalities. We use this method to study coupling between cerebral blood flow, amplitude of low frequency fluctuations, and local connectivity in 803 subjects ages 8 through 22. We demonstrate that coupling is spatially heterogeneous, varies with respect to age and sex in neurodevelopment, and reveals patterns that are not present in individual modalities. As availability of multi-modal data continues to increase, principal-component-based IMCo (pIMCo) offers a powerful approach for summarizing relationships between multiple aspects of brain structure and function. An R package for estimating pIMCo is available at: https://github.com/hufengling/pIMCo.

## Keywords {-}
Intermodal coupling; neurodevelopment; MRI; connectivity; resting state fMRI; cerebral blood flow 
^[Abbreviations: IMCo - intermodal coupling, pIMCo - principal-component-analysis-based intermodal coupling; SC - structural connectivity; FC - functional connectivity; CBF - cerebral blood flow; ALFF - amplitude of low-frequency fluctuations; ReHo - regional homogeneity; WLR - weighted linear regression; PCA - principal component analysis; PNC - Philadelphia Neurodevelopmental Cohort; rfMRI - resting-state functional MRI; ASL - arterial spin labeling; pcASL - pseudo-continuous arterial spin labeling; MPRAGE - magnetization-prepared, rapid-acquisition gradient echo; BOLD - blood oxygen level dependent; ANTS - Advanced Normalization Tools; XCP - eXtensible Connectivity Pipeline; BASIL - Bayesian Inference for Arterial Spin Labeling MRI; FWHM - full width at half maximum; AAL - Automated Anatomical Labeling]

\newpage
