---
title: "Voxel-wise Intermodal Coupling Analysis of Two or More Modalities using Local Covariance Decomposition"
author:
  - Fengling Hu:
      email: fengling.hu@pennmedicine.upenn.edu; 423 Guardian Dr, Philadelphia, PA 19104
      institute: pennsive
      correspondence: true
  - name: Sarah M. Weinstein
    institute: pennsive
  - name: Erica B. Baller
    institute: [psych, pennlinc]
  - name: Alessandra M. Valcarcel
    institute: pennsive
  - name: Azeez Adebimpe
    institute: pennlinc
  - name: Armin Raznahan
    institute: nimh
  - name: David R. Roalf
    institute: psych
  - name: Timothy E. Robert-Fitzgerald
    institute: pennsive
  - name: Virgilio Gonzenbach
    institute: pennsive
  - name: Ruben C. Gur
    institute: [psych, rad, neuro]
  - name: Raquel E. Gur
    institute: [psych, rad, neuro]
  - name: Simon Vandekar
    institute: vandybiostats
  - name: John A. Detre
    institute: neuro
  - name: Kristin A. Linn
    institute: pennsive
  - name: Aaron Alexander-Bloch
    institute: psych
  - name: Theodore D. Satterthwaite*
    institute: pennlinc
  - name: Russell T. Shinohara*
    institute: [pennsive, cbica]
institute:
  - pennsive: Penn Statistics in Imaging and Visualization Endeavor (PennSIVE), Department of Biostatistics, Epidemiology, and Informatics, Perelman School of Medicine, University of Pennsylvania
  - psych: Department of Psychiatry, Perelman School of Medicine, University of Pennsylvania
  - pennlinc: The Penn Lifespan Informatics and Neuroimaging Center, Department of Psychiatry, Perelman School of Medicine, University of Pennsylvania
  - nimh: National Institute of Mental Health, Intramural Research Program, National Institute of Health
  - rad: Department of Radiology, Perelman School of Medicine, University of Pennsylvania
  - neuro: Department of Neurology, Perelman School of Medicine, University of Pennsylvania
  - vandybiostats: Department of Biostatistics, Vanderbilt University
  - cbica: Center for Biomedical Image Computing and Analytics (CBICA), Perelman School of Medicine
date: '`r format(Sys.time(), "%d %B, %Y")`'
site: bookdown::bookdown_site
output:
  bookdown::word_document2:
    fig_caption: yes
    number_sections: yes
    global_numbering: yes
    md_extensions: +footnotes
    reference_docx: /Users/hufengling/Documents/Penn/Shinohara/bookdown_refs/word_style_reference.docx
    pandoc_args:
      - '--lua-filter=scholarly-metadata.lua'
      - '--lua-filter=author-info-blocks.lua'
    toc: no
bibliography: [ref.bib, references.bib, packages.bib]
fontsize: 12pt
link-citations: yes
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/elsevier-harvard.csl
---

# CRediT author statement {-}
**Fengling Hu:** Conceptualization, Methodology, Software, Validation, Formal analysis, Investigation, Writing -- Original Draft, Writing -- Review & Editing, Visualization. **Sarah M. Weinstein:** Methodology, Software, Formal analysis, Investigation, Writing -- Review & Editing. **Erica B. Baller:** Investigation, Resources, Writing -- Review & Editing. **Alessandra M. Valcarcel:** Conceptualization, Methodology, Software, Investigation. **Azeez Adebimpe:** Software, Investigation, Resources, Data Curation. **Armin Raznahan:** Conceptualization, Writing -- Review & Editing. **David R. Roalf:** Conceptualization, Writing -- Review & Editing. **Timothy E. Robert-Fitzgerald:** Methodology, Software, Data Curation, Visualization. **Virgilio Gonzenbach:** Methodology, Software, Visualization. **Ruben C. Gur:** Conceptualization, Investigation, Resources, Funding acquisition. **Raquel E. Gur:** Conceptualization, Investigation, Resources, Funding acquisition. **Simon Vandekar:** Conceptualization, Software, Formal analysis, Investigation, Writing -- Review & Editing. **John A. Detre:** Conceptualization, Writing -- Review & Editing. **Kristin A. Linn:** Conceptualization, Software, Formal analysis, Investigation, Writing -- Review & Editing, Funding acquisition. **Aaron Alexander-Bloch:** Methodology, Software, Formal analysis, Investigation, Resources. **Theodore D. Satterthwaite:** Conceptualization, Validation, Investigation, Resources, Data Curation, Writing -- Review & Editing, Supervision, Project administration, Funding acquisition. **Russell T. Shinohara:** Conceptualization, Methodology, Validation, Investigation, Resources, Writing -- Review & Editing, Supervision, Project administration, Funding acquisition

```{r include = FALSE}
knitr::opts_chunk$set(fig.width=5, fig.height=3.5, echo = FALSE, warning = FALSE, message = FALSE) 
```

\newpage
