---
title: "IMCo Validation - Three Modality ISLA"
author: "Fengling Hu"
output: html_document
---

# Setup
```{r, include = FALSE}
library(tidyverse)
library(ANTsRCore)
library(extrantsr)
library(IMCo)
library(here)
```

## File names
```{r}
idemo_qa <- read_csv(here("input/csvs/idemodata/n1601_idemo_FinalQA_092817.csv"))
idemo <- read_csv(here("input/csvs/idemodata/n1601_idemoBehavior_20151130.csv"))
idemo_health <- read_csv(here("input/csvs/idemodata/n1601_health_20170421.csv"))
pnc_demographics <- read_csv(here("input/csvs/demographics/binded_demographics.csv"))

idemo_qa <- idemo_qa %>% filter(idemoExcludeVoxelwise == 0)
idemo <- idemo %>% filter(idemoBehHappyCorrectCount >= 8)
idemo_health <- idemo_health %>% filter(ltnExcludev2 == 0)
pnc_demographics <- pnc_demographics %>% rename(scanid = "id")

common_pts <- Reduce(intersect, list(idemo_qa$scanid, idemo$scanid, idemo_health$scanid, pnc_demographics$scanid)) %>%
  as.data.frame() %>%
  rename(subj_num = ".")

input_filepaths <- common_pts %>% 
  mutate(modality_1 = paste0(subj_num, "_alffStd.nii.gz") %>% file.path("input/niftis/alff", .) %>% here(),
         modality_2 = paste0(subj_num, "_asl_quant_ssT1Std.nii.gz")%>% file.path("input/niftis/cbf", .) %>% here(), 
         modality_3 = paste0(subj_num, "_sigchange_cope1_TaskStd.nii.gz") %>% file.path("input/niftis/idemo", .) %>% here())

write_csv(input_filepaths, here("input/csvs/input_filepaths.csv"))

rm(common_pts, idemo, idemo_health, idemo_qa)
```

## Global Settings
```{r}
output_dir <- here("output") #base directory for all outputs
input_dir <- here("input") #base directory for all inputs
nifti_dir <- file.path(input_dir, 
                       list("niftis/alff",
                            "niftis/cbf",
                            "niftis/idemo"))
mask_path <- file.path(input_dir, "references/masks/gm10_pcals_rest.nii.gz")
input_filepaths <- read_csv(file.path(input_dir, "csvs/input_filepaths.csv"))
batch_script_dir <- here("R/batch_scripts")

fwhm <- 3
propMiss <- 0.9

settings <- list(input_filepaths_path = file.path(input_dir, "csvs/input_filepaths.csv"),
              output_dir = output_dir,
              input_dir = input_dir,
              nifti_dir = nifti_dir,
              batch_script_dir = batch_script_dir,
              mask_path = mask_path,
              fwhm = fwhm,
              propMiss = propMiss)

save(settings, file = file.path(input_dir, "csvs/settings.RData"))

```

# Intermodal Coupling
```{r}
bash_file <- rep(0, nrow(input_filepaths))
for(i in 1:nrow(input_filepaths)) {
  line <- input_filepaths[i, ]
  out_name <- line[1]
  subject_files <- paste(line[1, 2], line[1, 3], line[1, 4], sep = ",")
  
  bsub_args <- paste("bsub",
                     "-q taki_normal",
                     paste("-J", shQuote("intermodal_coupling")),
                     paste("-R", shQuote("rusage[mem=4000]")),
                     "-M 10000",
                     paste("-o", file.path(settings$output_dir, "stdout/intermodal_coupling.txt")))
  
  Rscript_args <- paste("Rscript", here("R/batch_scripts/01_perform_imco.R"),
                        subject_files,
                        settings$mask_path,
                        settings$output_dir,
                        out_name)
  bash_file[i] <- paste(bsub_args, Rscript_args)
  # system2("Rscript", args = c("R/batch_scripts/01_perform_imco.R",
  #                             subject_files,
  #                             settings$mask_path,
  #                             settings$output_dir,
  #                             out_name
  # ))
}

write_lines(bash_file, file.path(settings$batch_script_dir, "01_commands.sh"))
```

