---
title: "IMCo_ALFF_ISLA_IDEMO"
author: "Fengling Hu"
output: html_document
---

# Setup
```{r, include = FALSE}
library(tidyverse)
library(ANTsRCore)
library(extrantsr)
library(IMCo)
library(parallel)
library(here)
library(freesurfer)
```

## Load niftis
```{r}
idemo_qa <- read_csv(here("input/csvs/idemodata/n1601_idemo_FinalQA_092817.csv"))
idemo <- read_csv(here("input/csvs/idemodata/n1601_idemoBehavior_20151130.csv"))
idemo_health <- read_csv(here("input/csvs/idemodata/n1601_health_20170421.csv"))
pnc_demographics <- read_csv(here("input/csvs/demographics/binded_demographics.csv"))
isla_subj <- read_table(here("input/csvs/demographics/isla_subj.txt"), col_names = FALSE)

idemo_qa <- idemo_qa %>% filter(idemoExcludeVoxelwise == 0)
idemo <- idemo %>% filter(idemoBehHappyCorrectCount >= 8)
idemo_health <- idemo_health %>% filter(ltnExcludev2 == 0)
pnc_demographics <- pnc_demographics %>% rename(scanid = "id")
isla_subj <- isla_subj %>% separate(X1, c("scanid", "file_root"), sep = "_")

common_pts <- Reduce(intersect, list(idemo_qa$scanid, idemo$scanid, idemo_health$scanid, pnc_demographics$scanid, isla_subj$scanid)) %>%
  as.data.frame() %>%
  rename(subj_num = ".")

input_filepaths <- common_pts %>% 
  mutate(modality_1 = paste0(subj_num, "_alffStd.nii.gz") %>% file.path("~/Documents/IMCo_analyses/input/niftis/alff", .),
         modality_2 = paste0(subj_num, "_predictedGMD1.nii.gz") %>% file.path("~/Documents/IMCo_analyses/input/niftis/cbf_isla", .), 
         modality_3 = paste0(subj_num, "_sigchange_cope1_TaskStd.nii.gz") %>% file.path("~/Documents/IMCo_analyses/input/niftis/idemo", .))

input_filepaths$subj_num <- as.numeric(input_filepaths$subj_num)
  
write_csv(input_filepaths, here("input/csvs/input_filepaths.csv"))

rm(pnc_demographics, common_pts, idemo, idemo_health, idemo_qa, isla_subj)
```

## Load non-nifti PNC data
```{r}
demographics <- read_csv(here("input/csvs/demographics/binded_demographics.csv")) %>% 
  rename(subj_num = id)
demographics <- right_join(demographics, input_filepaths, 
                           by = "subj_num") %>% 
  mutate(across(contains("Exclude"), as.factor),
         sex = case_when(
           sex == 1 ~ "Male",
           sex == 2 ~ "Female",
           T ~ NA_character_),
         race2 = case_when(
           race2 == 1 ~ "White",
           race2 == 2 ~ "Black",
           race2 == 3 ~ "Other",
           T ~ NA_character_),
         across(c(sex, race, race2, ethnicity, handednessv2), as.factor))
predictors <- demographics %>%
  select(sex, ageAtScan1, race2, pcaslRelMeanRMSMotion, restRelMeanRMSMotion)

write_csv(predictors, file.path(here("input/csvs/predictors.csv")))
rm(demographics)
```

## Write settings
```{r}
output_dir <- here("output") #base directory for all outputs
input_dir <- here("input") #base directory for all inputs
nifti_dir <- "~/Documents/IMCo_analyses/input/niftis"
batch_script_dir <- here("R/batch_scripts")
input_filepaths_path = file.path(input_dir, "csvs/input_filepaths.csv")
mask_path <- file.path(input_dir, "references/masks/gm10_pcals_rest.nii.gz")
predictors_path <- file.path(input_dir, "csvs/predictors.csv")
settings_path <- file.path(input_dir, "csvs/settings.RData")
fwhm <- 3
prop_miss <- 0.9

settings <- list(output_dir = output_dir,
                 input_dir = input_dir,
                 nifti_dir = nifti_dir,
                 batch_script_dir = batch_script_dir,
                 input_filepaths_path = input_filepaths_path,
                 mask_path = mask_path,
                 predictors_path = predictors_path,
                 settings_path = settings_path,
                 fwhm = fwhm,
                 prop_miss = prop_miss)

input_filepaths <- read_csv(file.path(settings$input_dir, "csvs/input_filepaths.csv"))

save(settings, file = file.path(settings$input_dir, "csvs/settings.RData"))

rm(output_dir, input_dir, nifti_dir, batch_script_dir, input_filepaths_path, mask_path, predictors_path, settings_path, fwhm, prop_miss)
```

# Write IMCo bash script
```{r}
bash_file <- rep(0, nrow(input_filepaths))
for(i in 1:nrow(input_filepaths)) {
  line <- input_filepaths[i, ]
  out_name <- line[1]
  subject_files <- paste(line[1, 2], line[1, 3], line[1, 4], sep = ",")
  
  bsub_args <- paste("bsub",
                     "-q taki_normal",
                     paste("-J", shQuote("intermodal_coupling")),
                     paste("-R", shQuote("rusage[mem=4000]")),
                     "-M 10000",
                     paste("-o", file.path(settings$output_dir, "stdout/intermodal_coupling.txt")))
  
  Rscript_args <- paste("Rscript", file.path(settings$batch_script_dir, "01_perform_imco.R"),
                        subject_files,
                        settings$mask_path,
                        settings$output_dir,
                        out_name,
                        settings$fwhm,
                        settings$prop_miss)
  bash_file[i] <- paste(bsub_args, Rscript_args)
}

write_lines(bash_file, file.path(settings$batch_script_dir, "01_commands.sh"))
#RUNOTHER

rm(bash_file, i, line, out_name, subject_files, bsub_args, Rscript_args)
```

# Write calculate_pvals bash script
```{r}
cores <- 8
global_wcov <- c(settings$settings_path, file.path(settings$output_dir, "niftis/coupled/global_wcov"), cores, NA, NA)
unscaled_wcor <- c(settings$settings_path, file.path(settings$output_dir, "niftis/coupled/unscaled_wcor"), cores, NA, NA)
alff <- c(settings$settings_path, file.path(settings$nifti_dir, "alff"), cores, TRUE, 1)
idemo <- c(settings$settings_path, file.path(settings$nifti_dir, "idemo"), cores, TRUE, 2)
cbf_isla <- c(settings$settings_path, file.path(settings$nifti_dir, "cbf_isla"), cores, TRUE, 3)

pvals_to_calculate <- list(global_wcov, unscaled_wcor, alff, idemo, cbf_isla)

bash_file <- rep(0, length(pvals_to_calculate))
for(i in 1:length(pvals_to_calculate)) {
  to_analyze <- pvals_to_calculate[[i]]
  
  Rscript_args <- paste("Rscript", file.path(settings$batch_script_dir, "02_calculate_pvals.R"),
                        to_analyze[1],
                        to_analyze[2],
                        to_analyze[3],
                        to_analyze[4],
                        to_analyze[5])
  bash_file[i] <- paste(Rscript_args)
}

write_lines(bash_file, file.path(settings$batch_script_dir, "02_commands.sh"))
#RUNOTHER
```

## Run
```{r}
analyze_coupled_images(nifti_dir = file.path(settings$output_dir, "niftis/coupled/global_wcov"),
                       mask = settings$mask_path,
                       predictors = predictors,
                       cores = 8)
analyze_coupled_images(nifti_dir = file.path(settings$output_dir, "niftis/coupled/unscaled_wcor"),
                       mask = settings$mask_path,
                       predictors = predictors,
                       cores = 8)
analyze_coupled_images(nifti_dir = file.path(settings$nifti_dir, "alff"), #TOCHANGE
                       mask = settings$mask_path,
                       predictors = predictors,
                       cores = 8,
                       is_modality = TRUE,
                       file_paths = input_filepaths$modality_1 %>% as.list())
analyze_coupled_images(nifti_dir = file.path(settings$nifti_dir, "idemo"), #TOCHANGE
                       mask = settings$mask_path,
                       predictors = predictors,
                       cores = 8,
                       is_modality = TRUE,
                       file_paths = input_filepaths$modality_2 %>% as.list())
analyze_coupled_images(nifti_dir = file.path(settings$nifti_dir, "cbf_isla"), #TOCHANGE
                       mask = settings$mask_path,
                       predictors = predictors,
                       cores = 8,
                       is_modality = TRUE,
                       file_paths = input_filepaths$modality_3 %>% as.list())
```


# Perform multiple comparisons

## Functions
```{r}
get_file_name <- function(file_path, pval_name) {
  split_path <- file_path %>% str_split("/")
  full_name <- split_path[[1]][length(split_path[[1]])]
  file_name <- full_name %>% str_remove(".nii.gz")
  
  if (!is.null(pval_name)) {
    file_name <- file_name %>% sub("pval.*", pval_name, .)
  }
  
  return(file_name)
}

process_pval_image <- function(file_path, mask, out_dir, pval_name) {
  mask <- extrantsr::check_ants(mask)
  file_name <- get_file_name(file_path, pval_name)
  pval_image <- check_ants(file_path)
  pval_numeric <- pval_image %>% as.numeric()
  pval_numeric_clean <- pval_numeric[pval_numeric != 0]
  bonferroni_adjusted <- p.adjust(pval_numeric_clean, method = "bonferroni")
  fdr_adjusted <- p.adjust(pval_numeric_clean, method = "fdr")
  
  mask_indices <- which(as.array(mask) > 0)
  
  unadjusted <- convert_to_ants(pval_numeric_clean, 0.05, mask_indices, pval_image)
  bonferroni <- convert_to_ants(bonferroni_adjusted, 0.05, mask_indices, pval_image)
  fdr_image_0.05 <- convert_to_ants(fdr_adjusted, 0.05, mask_indices, pval_image)
  
  dir.create(out_dir, showWarnings = FALSE)
  
  antsImageWrite(unadjusted, file.path(out_dir, paste0(file_name, "_unadjusted.nii.gz")))
  antsImageWrite(bonferroni, file.path(out_dir, paste0(file_name, "_bonferroni.nii.gz")))
  antsImageWrite(fdr_image_0.05, file.path(out_dir, paste0(file_name, "_fdr05.nii.gz")))
  
  return(NULL)
}

convert_to_ants <- function(adjusted_pvals, threshold, mask_indices, reference) {
  adjusted_pvals[adjusted_pvals > threshold] <- 0
  adjusted_pvals[adjusted_pvals != 0] <- 1
  
  adjusted_image <- make_ants_image(adjusted_pvals, mask_indices, reference)
  
  return(adjusted_image)
}

name_pvals <- function(pval_files, pval_names) {
  lapply(pval_files,
         function(pval_file, pval_names) {
           pval_num <- str_extract(pval_file, ".\\.nii\\.gz") %>%
             str_remove("\\.nii\\.gz") %>%
             as.numeric()
           pval_names[pval_num]
         },
         pval_names = pval_names)
}
```

## Run
```{r}
raw_pvals_dir <- file.path(settings$output_dir, "niftis/pvals/raw")

raw_pval_files <- file.path(raw_pvals_dir, list.files(raw_pvals_dir, ".nii.gz"))
pval_names <- c("sex", "age", "sex-age")
pval_name_list <- name_pvals(raw_pval_files, pval_names)

mapply(process_pval_image,
       file_path = raw_pval_files,
       pval_name = pval_name_list,
       MoreArgs = list(
         mask = settings$mask_path,
         out_dir = file.path(settings$output_dir, "niftis/pvals/adjusted")))
```

# Get p-value descriptive stats
## Functions
```{r}
get_file_names <- function(pval_directory) {
  pval_names <- file.path(pval_directory) %>%
    list.files()
  c(pval_names) %>% sub(".nii.gz", "", .)
}

load_pval_images <- function(pval_directory) {
  pval_files <- file.path(pval_directory) %>% list.files(full.names = TRUE)
  
  check_ants(pval_files)
}

get_metadata <- function(pval_names, pval_directory) {
  pval_files <- file.path(pval_directory) %>% list.files(full.names = TRUE)
  
  metadata_df <- pval_names %>%
    str_split("_") %>%
    as.data.frame() %>%
    t() %>%
    as.data.frame()
  rownames(metadata_df) <- 1:nrow(metadata_df)
  colnames(metadata_df) <- c("scaling", "matrix_type", "coefficient", "mc_correction")
  
  metadata_df <- metadata_df %>% mutate(file_paths = pval_files)
  
  metadata_df
}

get_descriptive_stats <- function(pval_image, gm_mask) {
  total_voxels <- sum(gm_mask)
  prop_sig <- sum(pval_image) / total_voxels
  
  data.frame(prop_sig)
}

process_pval_images <- function(pval_directory, gm_mask, image_format = c("ants", "nifti")) {
  gm_mask <- check_ants(gm_mask)
  pval_images <- load_pval_images(pval_directory)
  pval_names <- get_file_names(pval_directory)
  pval_metadata <- get_metadata(pval_names, pval_directory)
  
  pval_metadata_list <- split(pval_metadata, seq(nrow(pval_metadata)))
  
  descriptive_stats <- lapply(pval_images,
                              get_descriptive_stats,
                              gm_mask)
  
  descriptive_stats_df <- descriptive_stats %>%
    unlist() %>%
    as.matrix(byrow = T, ncol = ncol(pval_metadata)) %>%
    as.data.frame()
  names(descriptive_stats_df) <- c("prop_sig")
  rownames(descriptive_stats_df) <- 1:nrow(pval_metadata)
  
  pval_info <- cbind(pval_metadata, descriptive_stats_df)
  
  if (image_format == "nifti") {
    pval_images <- lapply(pval_images, ants2oro)
  }
  
  list(pval_info, pval_images)
}

view_itksnap <- function(pval_info,
                         pval_mask_filter = "brain",
                         directory_filter = NULL,
                         segmentation = NULL,
                         scaling_filter = NULL,
                         fwhm_filter = NULL,
                         coefficient_filter = NULL,
                         mc_correction_filter = NULL,
                         pca_mask_filter = NULL,
                         show_image = TRUE) {
  if (class(segmentation) == "antsImage") {
    segmentation <- ants2oro(segmentation)
  }
  
  tmp <- pval_info
  
  if (!is.null(directory_filter)) {
    tmp <- tmp %>% filter(directory == directory_filter)
  }
  if (!is.null(pval_mask_filter)) {
    tmp <- tmp %>% filter(pval_mask == pval_mask_filter)
  }
  if (!is.null(scaling_filter)) {
    tmp <- tmp %>% filter(scaling == scaling_filter)
  }
  if (!is.null(fwhm_filter)) {
    tmp <- tmp %>% filter(fwhm == fwhm_filter)
  }
  if (!is.null(coefficient_filter)) {
    tmp <- tmp %>% filter(coefficient == coefficient_filter)
  }
  if (!is.null(mc_correction_filter)) {
    tmp <- tmp %>% filter(mc_correction == mc_correction_filter)
  }
  if (!is.null(pca_mask_filter)) {
    tmp <- tmp %>% filter(pca_mask == pca_mask_filter)
  }
  
  print(tmp$prop_sig)
  print(tmp$file_path)
  
  
  file_paths <- tmp$file_paths
  
  if (show_image) {
    if (length(file_paths) == 2) {
      itksnap(file_paths[1], overlay = file_paths[2], segmentation, verbose = F)
    } else {
      for (i in 1:length(file_paths)) {
        itksnap(file_paths[i], segmentation = segmentation, verbose = F)
      }
    }
  }
  
  return(NULL)
}
```

## Run
```{r}
pval_dir <- file.path(settings$output_dir, "niftis/pvals")

pval_image_stats <- process_pval_images(file.path(pval_dir, "adjusted"), settings$mask_path, image_format = "nifti")
pval_stats_df <- pval_image_stats[[1]]
view_itksnap(pval_stats_df,
             pval_mask_filter = NULL,
             directory_filter = "adjusted_gm",
             segmentation = gm_mask,
             scaling_filter = "unscaled",
             fwhm_filter = "fwhm3",
             coefficient_filter = NULL,
             mc_correction_filter = "fdr05",
             pca_mask_filter = "gm-mask",
             show_image = TRUE)

write_csv(pval_stats_df, file.path(settings$output_dir, "csvs/pval_descriptive_stats.csv"))
```

# Generate barcharts
## Functions
```{r}
get_prop_sig <- function(file_paths, file_labels, atlas, mask) {
  pval_masks <- check_ants(file_paths)
  mask <- check_ants(mask)
  
  masked_atlas <- atlas * mask
  network_ids <- masked_atlas[masked_atlas != 0] %>%
    as.factor() %>%
    summary() %>%
    names()
  
  common_mask <- atlas * mask
  common_mask[common_mask != 0] <- 1
  
  sig_voxel_images <- lapply(pval_masks, function(pval_mask) pval_mask * masked_atlas)
  nonsig_voxel_images <- lapply(pval_masks, function(pval_mask) (-pval_mask + 1) * masked_atlas)
  
  for (i in 1:4) {
    sig_sum <- sum(sig_voxel_images[[i]] != 0)
    nonsig_sum <- sum(nonsig_voxel_images[[i]] != 0)
    if (sum(common_mask) != nonsig_sum + sig_sum) {
      stop()
    }
  }
  
  summaries <- mapply(
    function(sig_voxel_image, nonsig_voxel_image, file_label, network_id) {
      sig_summary <- sig_voxel_image[sig_voxel_image != 0] %>%
        as.factor() %>%
        summary() %>%
        as.data.frame() %>%
        rownames_to_column() %>%
        rename(sig_counts = ".")
      
      nonsig_summary <- nonsig_voxel_image[nonsig_voxel_image != 0] %>%
        as.factor() %>%
        summary() %>%
        as.data.frame() %>%
        rownames_to_column() %>%
        rename(nonsig_counts = ".")
      
      map_name <- rep(file_label, length(network_ids))
      
      df <- data.frame(network_ids) %>%
        cbind(map_name) %>%
        left_join(sig_summary, by = c("network_ids" = "rowname")) %>%
        left_join(nonsig_summary, by = c("network_ids" = "rowname"))
      
      return(df)
    },
    sig_voxel_images, nonsig_voxel_images, file_labels,
    MoreArgs = list(network_ids),
    SIMPLIFY = FALSE)
  
  summaries_df <- bind_rows(summaries) %>%
    mutate(proportion = sig_counts / (sig_counts + nonsig_counts),
           se = sqrt(proportion * (1 - proportion) / (sig_counts + nonsig_counts))
    )
  
  return(summaries_df)
}
```

## Run
```{r}
pvals_dir <- file.path(settings$output_dir, "niftis/pvals")
pval_metadata <- read_csv(file.path(settings$output_dir, "csvs", "pval_descriptive_stats.csv"))
yeo7 <- file.path(settings$input_dir, "references/atlases/7yeonetworkPNC.nii.gz") %>% check_ants()
aal <- file.path(settings$input_dir, "references/atlases/AAL_atlas_PNC.nii.gz") %>% check_ants()


# transform aal to yeo7-style mask
aal_sym <- floor(aal/10) * 10

all_indices <- unique(aal_sym)
subcortical_indices <- c(4100, 4200, 7000, 7010, 7020, 7100) # What are the subcortical structures?

excluded_indices <- all_indices[!all_indices %in% subcortical_indices]

for(i in 1:length(excluded_indices)) {
  aal_sym[aal_sym == excluded_indices[i]] <- 0
}

file_labels <- c("global_age", "global_sex", "unscaled_age", "unscaled_sex")

# get file paths
file_paths <- pval_metadata %>%
  filter(coefficient == "sex" | coefficient == "age",
         mc_correction == "fdr05") %>%
  pull(file_paths)

yeo7_df <- get_prop_sig(file_paths, file_labels, yeo7, settings$mask_path)
yeo7_barplot <- ggplot(yeo7_df, aes(network_ids, proportion)) +
  geom_col() +
  geom_errorbar(aes(ymin = proportion - se, ymax = proportion + se), width = .2,
                position = position_dodge(.9)) +
  facet_wrap(~ map_name) +
  labs(title = "PCA on Yeo7") +
  scale_x_discrete(labels = c("Visual", "Somatomotor", "Dorsal Attention", "Ventral Attention", "Limbic", "Frontoparietal", "Default")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)); yeo7_barplot
ggsave(plot = yeo7_barplot, file.path(settings$output_dir, "figures", "yeo7_pval-prop_fdr05.png"), type = "cairo-png")

aal_sym_df <- get_prop_sig(file_paths, file_labels, aal_sym, settings$mask_path)
aal_barplot <- ggplot(aal_sym_df, aes(network_ids, proportion)) +
  geom_col() +
  geom_errorbar(aes(ymin = proportion - se, ymax = proportion + se), width = .2,
                position = position_dodge(.9)) +
  facet_wrap(~ map_name) +
  labs(title = "PCA on AAL") +
  scale_x_discrete(labels = c("Hippocampus", "Amygdala", "Caudate", "Putamen", "Pallidum", "Thalamus")) +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 90)); aal_barplot
ggsave(plot = aal_barplot, file.path(settings$output_dir, "figures", "aal_pval-prop_fdr05.png"), type = "cairo-png")


# # ---------------------------------------------------
# TODO
# raw_file_paths <- file.path(dir, "adjusted_gm") %>%
#   list.files()
# raw_file_path_select <- raw_file_paths %>%
#   (function(x) grepl("alff|cbf", x) &
#      grepl("_sex_|_age_", x) &
#      grepl("bonferroni", x))
# raw_file_paths <- file.path(file.path(dir, "adjusted_gm"), raw_file_paths[raw_file_path_select])
# raw_file_labels <- c("alff_age", "alff_sex", "cbf_age", "cbf_sex")
# 
# yeo7_df_raw <- get_prop_sig(raw_file_paths, raw_file_labels, yeo7, gm_mask)
# ggplot(yeo7_df_raw, aes(network_ids, proportion)) +
#   geom_col() +
#   geom_errorbar(aes(ymin = proportion - se, ymax = proportion + se), width = .2,
#                 position = position_dodge(.9)) +
#   facet_wrap(~ map_name) +
#   labs(title = "Raw on Yeo7") +
#   theme_classic()
# 
# aal_sym_df_raw <- get_prop_sig(raw_file_paths, raw_file_labels, aal_sym, gm_mask)
# ggplot(aal_sym_df_raw, aes(network_ids, proportion)) +
#   geom_col() +
#   geom_errorbar(aes(ymin = proportion - se, ymax = proportion + se), width = .2,
#                 position = position_dodge(.9)) +
#   facet_wrap(~ map_name) +
#   labs(title = "Raw on AAL") +
#   theme_classic()
```

# Process/transform/project regions to prepare for Spin Test
## Functions
```{r}
source(here("R/mri_vol2surf.R"))

split_atlas_into_regions <- function(atlas, atlas_name = c("yeo7", "aal"), region_out_dir) {
  dir.create(region_out_dir, showWarnings = FALSE)
  atlas[atlas == 0] <- NA
  region_names <- atlas %>%
    as.factor() %>%
    summary() %>%
    names()
  region_names <- region_names[-length(region_names)]
  out_file_names <- region_names %>%
    paste0(atlas_name, "_", ., ".nii.gz") %>%
    file.path(region_out_dir, .)
  
  mapply(
    function(region_name, out_file_name) {
      temp <- atlas * 1 # causes R to make a copy of atlas at a new address
      temp[atlas == region_name] <- 1
      temp[atlas != region_name] <- 0
      
      antsImageWrite(temp, out_file_name)
    }, as.numeric(region_names),
    out_file_names)
  
  return(out_file_names)
}

get_names <- function(paths) {
  names_list <- lapply(paths, function(path) {
    split_path <- str_split(path, "/") %>%
      unlist()
    file_name <- split_path[length(split_path)]
  })
  unlist(names_list)
}

transform_to_MNI <- function(images, paths, MNI_transform_out_dir) {
  MNI <- check_ants(file.path(settings$input_dir, "references/atlases/MNI152_T1_1mm_brain.nii.gz"))
  transform_list <- c(file.path(settings$input_dir, "transformations/PNC-MNI_0Warp.nii.gz"),
                      file.path(settings$input_dir, "transformations/PNC-MNI_1Affine.mat"))
  file_names <- get_names(paths)
  
  mapply(function(image, file_name, MNI, transform_list) {
    image_transformed <- antsApplyTransforms(fixed = MNI,
                                             moving = image,
                                             transformlist = transform_list,
                                             interpolator = "nearestNeighbor",
                                             imagetype = 0)
    
    antsImageWrite(image_transformed, file.path(MNI_transform_out_dir, file_name))
    
    return(file.path(MNI_transform_out_dir, file_name))
  }, image = images, file_name = file_names,
  MoreArgs = list(MNI = MNI, transform_list = transform_list))
}

project_to_surface <- function(image_MNI_paths, out_dir) {
  dir.create(out_dir, showWarnings = FALSE)
  hemi_paths <- lapply(image_MNI_paths, function(image_path) {
    outfile = get_names(image_path)
    lh <- mri_vol2surf(mov = image_path,
                       target_subject = 'fsaverage',
                       opts = "--interp nearest",
                       outfile = file.path(out_dir, outfile),
                       hemi = "lh")
    rh <- mri_vol2surf(mov = image_path,
                       target_subject = 'fsaverage',
                       opts = "--interp nearest",
                       outfile = file.path(out_dir, outfile),
                       hemi = "rh")
    c(file.path(lh), file.path(rh))
  })
  
  num_files <- length(hemi_paths)
  paths_df <- hemi_paths %>%
    unlist() %>%
    matrix(byrow = TRUE, ncol = 1) %>%
    as.data.frame() %>%
    rename(paths = "V1") %>%
    mutate(hemisphere = rep(c("lh", "rh"), num_files))
  
  paths_df
}

preprocess_for_spin_test <- function(file_paths = NULL, atlas_name = c("", "yeo7", "aal"),
                                     fs_images_dir,
                                     file_path_output_dir = "") {
  if (is.null(file_paths)) {
    if (atlas_name == "yeo7") {
      atlas <- check_ants(file.path(settings$input_dir, "references/atlases/7yeonetworkPNC.nii.gz"))
      atlas_output_dir <- "yeo7_regions"
    }

    if (atlas_name == "aal") {
      atlas <- check_ants(file.path(settings$input_dir, "references/atlases/AAL_atlas_PNC.nii.gz"))
      atlas_output_dir <- "aal_regions"
      for(i in 0:9) {
        lower <- i * 1000
        upper <- (i + 1) * 1000
        atlas[atlas >= lower & atlas < upper] <- lower
      }
    }
    
    region_paths <- split_atlas_into_regions(atlas,
                                             atlas_name = atlas_name,
                                             file.path(fs_images_dir, "PNC_space", atlas_output_dir))
    region_images <- check_ants(region_paths)
    region_transformed_paths <- transform_to_MNI(region_images,
                                                 region_paths,
                                                 file.path(fs_images_dir, "MNI_space", atlas_output_dir))
    region_sphere <- project_to_surface(region_transformed_paths,
                                        file.path(fs_images_dir, "surfaces", atlas_output_dir))
    
    return(NULL)
  }
  
  if (!is.null(file_paths)) {
    pval_images <- check_ants(file_paths)
    pval_transformed_paths <- transform_to_MNI(pval_images,
                                               file_paths,
                                               file.path(fs_images_dir, "MNI_space", file_path_output_dir))
    pval_sphere <- project_to_surface(pval_transformed_paths,
                                      file.path(fs_images_dir, "surfaces", file_path_output_dir))
    
    return(NULL)
  }
  # map_type <- c(rep("region", nrow(region_sphere)), rep("pval", nrow(pval_sphere)))
  # paths_df <- region_sphere %>%
  #   rbind(pval_sphere) %>%
  #   mutate(map_type = map_type)
  # 
  # write_csv(paths_df, file.path(fs_images_dir, "paths_to_surfaces.csv"))
  
  # paths_df
}
```

## Run
```{r}
Sys.setenv(FS_LICENSE="/home/fengling/software/freesurfer/license.txt")
pval_paths <- read_csv(file.path(settings$output_dir, "csvs/pval_descriptive_stats.csv")) %>% 
  filter(mc_correction == "fdr05") %>%
  pull(file_paths) %>% 
  as.list()
fs_images_dir <- file.path(settings$output_dir, "freesurfer_images")

preprocess_for_spin_test(atlas_name = "yeo7",
                         fs_images_dir = fs_images_dir)
preprocess_for_spin_test(atlas_name = "aal",
                         fs_images_dir = fs_images_dir)
preprocess_for_spin_test(file_paths = pval_paths,
                         fs_images_dir = fs_images_dir,
                         file_path_output_dir = "pvals/adjusted")
preprocess_for_spin_test()

```


